name: Check Markdown links

on:
  push:
    branches: [ main ]

job:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: "--verbose --no-progress README.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
